# Generated by Django 5.0.4 on 2024-04-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasts',
            new_name='Task',
        ),
    ]
